name: aws setup

on:
  push:
    branches:
      - main
    paths:
      - cloudformation/template.yml
      - .github/workflows/aws-setup.yml

env:
  AWS_REGION: us-east-1



jobs:
  cloudformation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Validate Template
        run: sam validate -t cloudformation/template.yml --lint
      - name: Deploy CloudFormation
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: TerraformAssumeRoleSetup
          template: cloudformation/template.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
      - name: Add Link to Workflow Summary
        run: |
          echo "[TerraformAssumeRoleSetup | CloudFormation | ${{ env.AWS_REGION }}](https://console.aws.amazon.com/cloudformation/home?region=${{ env.AWS_REGION }}#/stacks/stackinfo?filteringText=TerraformAssumeRoleSetup&stackId=${{ steps.deploy.outputs.stack-id }})" \
          >> $GITHUB_STEP_SUMMARY
