name: setup

on:
  pull_request:
    paths:
      - cloudformation/template.yml
      - .github/workflows/aws-config.yml
  push:
    branches:
      - main
    paths:
      - cloudformation/template.yml
      - .github/workflows/aws-config.yml

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  create-assume-role:
    name: terraform assume role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Validate Template
        run: sam validate -t cloudformation/template.yml --lint
      - name: Deploy CloudFormation
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: TerraformAssumeRoleSetup
          template: cloudformation/template.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
      - name: Add Link to Workflow Summary
        run: |
          echo "
          # AWS Resources\n
          - [TerraformAssumeRoleSetup | CloudFormation | ${{ env.AWS_REGION }}](https://console.aws.amazon.com/cloudformation/home?region=${{ env.AWS_REGION }}#/stacks/stackinfo?filteringText=TerraformAssumeRoleSetup&stackId=${{ steps.deploy.outputs.stack-id }})
          " 
          >> $GITHUB_STEP_SUMMARY
